// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VersionsValuesItemsMediaTypesItems versions values items media types items
// swagger:model versionsValuesItemsMediaTypesItems
type VersionsValuesItemsMediaTypesItems struct {

	// base
	// Enum: [application/json]
	Base string `json:"base,omitempty"`

	// type
	// Enum: [application/json]
	Type string `json:"type,omitempty"`
}

// Validate validates this versions values items media types items
func (m *VersionsValuesItemsMediaTypesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBase(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var versionsValuesItemsMediaTypesItemsTypeBasePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["application/json"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		versionsValuesItemsMediaTypesItemsTypeBasePropEnum = append(versionsValuesItemsMediaTypesItemsTypeBasePropEnum, v)
	}
}

const (

	// VersionsValuesItemsMediaTypesItemsBaseApplicationJSON captures enum value "application/json"
	VersionsValuesItemsMediaTypesItemsBaseApplicationJSON string = "application/json"
)

// prop value enum
func (m *VersionsValuesItemsMediaTypesItems) validateBaseEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, versionsValuesItemsMediaTypesItemsTypeBasePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *VersionsValuesItemsMediaTypesItems) validateBase(formats strfmt.Registry) error {

	if swag.IsZero(m.Base) { // not required
		return nil
	}

	// value enum
	if err := m.validateBaseEnum("base", "body", m.Base); err != nil {
		return err
	}

	return nil
}

var versionsValuesItemsMediaTypesItemsTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["application/json"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		versionsValuesItemsMediaTypesItemsTypeTypePropEnum = append(versionsValuesItemsMediaTypesItemsTypeTypePropEnum, v)
	}
}

const (

	// VersionsValuesItemsMediaTypesItemsTypeApplicationJSON captures enum value "application/json"
	VersionsValuesItemsMediaTypesItemsTypeApplicationJSON string = "application/json"
)

// prop value enum
func (m *VersionsValuesItemsMediaTypesItems) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, versionsValuesItemsMediaTypesItemsTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *VersionsValuesItemsMediaTypesItems) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VersionsValuesItemsMediaTypesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VersionsValuesItemsMediaTypesItems) UnmarshalBinary(b []byte) error {
	var res VersionsValuesItemsMediaTypesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
