// Code generated by go-swagger; DO NOT EDIT.

package keystone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/IBM/cloudland/web/rest-api/rest/models"
)

// PostIdentityV3AuthTokensReader is a Reader for the PostIdentityV3AuthTokens structure.
type PostIdentityV3AuthTokensReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIdentityV3AuthTokensReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostIdentityV3AuthTokensCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostIdentityV3AuthTokensCreated creates a PostIdentityV3AuthTokensCreated with default headers values
func NewPostIdentityV3AuthTokensCreated() *PostIdentityV3AuthTokensCreated {
	return &PostIdentityV3AuthTokensCreated{
		Vary: "X-Auth-Token",
	}
}

/*PostIdentityV3AuthTokensCreated handles this case with default header values.

successful operation
*/
type PostIdentityV3AuthTokensCreated struct {
	ContentLength int64
	/*X-Auth-Token
	 */
	Vary string

	XSubjectToken string

	Payload *models.PostIdentityV3AuthTokensCreatedBody
}

func (o *PostIdentityV3AuthTokensCreated) Error() string {
	return fmt.Sprintf("[POST /identity/v3/auth/tokens][%d] postIdentityV3AuthTokensCreated  %+v", 201, o.Payload)
}

func (o *PostIdentityV3AuthTokensCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Content-Length
	contentLength, err := swag.ConvertInt64(response.GetHeader("Content-Length"))
	if err != nil {
		return errors.InvalidType("Content-Length", "header", "int64", response.GetHeader("Content-Length"))
	}
	o.ContentLength = contentLength

	// response header Vary
	o.Vary = response.GetHeader("Vary")

	// response header X-Subject-Token
	o.XSubjectToken = response.GetHeader("X-Subject-Token")

	o.Payload = new(models.PostIdentityV3AuthTokensCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
