// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hypers.proto

package hypers

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Kind int32

const (
	Kind_all   Kind = 0
	Kind_hyper Kind = 1
	Kind_agent Kind = 2
)

var Kind_name = map[int32]string{
	0: "all",
	1: "hyper",
	2: "agent",
}

var Kind_value = map[string]int32{
	"all":   0,
	"hyper": 1,
	"agent": 2,
}

func (x Kind) String() string {
	return proto.EnumName(Kind_name, int32(x))
}

func (Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1e42abecf7719035, []int{0}
}

type Hyper struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname             string   `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Parentid             int32    `protobuf:"varint,5,opt,name=parentid,proto3" json:"parentid,omitempty"`
	Duration             int64    `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hyper) Reset()         { *m = Hyper{} }
func (m *Hyper) String() string { return proto.CompactTextString(m) }
func (*Hyper) ProtoMessage()    {}
func (*Hyper) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e42abecf7719035, []int{0}
}

func (m *Hyper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hyper.Unmarshal(m, b)
}
func (m *Hyper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hyper.Marshal(b, m, deterministic)
}
func (m *Hyper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hyper.Merge(m, src)
}
func (m *Hyper) XXX_Size() int {
	return xxx_messageInfo_Hyper.Size(m)
}
func (m *Hyper) XXX_DiscardUnknown() {
	xxx_messageInfo_Hyper.DiscardUnknown(m)
}

var xxx_messageInfo_Hyper proto.InternalMessageInfo

func (m *Hyper) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Hyper) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Hyper) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Hyper) GetParentid() int32 {
	if m != nil {
		return m.Parentid
	}
	return 0
}

func (m *Hyper) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type GetRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e42abecf7719035, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetReply struct {
	Hyper                *Hyper   `protobuf:"bytes,1,opt,name=hyper,proto3" json:"hyper,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReply) Reset()         { *m = GetReply{} }
func (m *GetReply) String() string { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()    {}
func (*GetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e42abecf7719035, []int{2}
}

func (m *GetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReply.Unmarshal(m, b)
}
func (m *GetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReply.Marshal(b, m, deterministic)
}
func (m *GetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReply.Merge(m, src)
}
func (m *GetReply) XXX_Size() int {
	return xxx_messageInfo_GetReply.Size(m)
}
func (m *GetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetReply proto.InternalMessageInfo

func (m *GetReply) GetHyper() *Hyper {
	if m != nil {
		return m.Hyper
	}
	return nil
}

type ListRequest struct {
	Parentid             int32    `protobuf:"varint,1,opt,name=parentid,proto3" json:"parentid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Kind                 Kind     `protobuf:"varint,3,opt,name=kind,proto3,enum=com.ibm.cloudland.hypers.Kind" json:"kind,omitempty"`
	Unscoped             bool     `protobuf:"varint,4,opt,name=unscoped,proto3" json:"unscoped,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e42abecf7719035, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetParentid() int32 {
	if m != nil {
		return m.Parentid
	}
	return 0
}

func (m *ListRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ListRequest) GetKind() Kind {
	if m != nil {
		return m.Kind
	}
	return Kind_all
}

func (m *ListRequest) GetUnscoped() bool {
	if m != nil {
		return m.Unscoped
	}
	return false
}

type DeleteRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e42abecf7719035, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

type DeleteReply struct {
	Deleted              int64    `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReply) Reset()         { *m = DeleteReply{} }
func (m *DeleteReply) String() string { return proto.CompactTextString(m) }
func (*DeleteReply) ProtoMessage()    {}
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e42abecf7719035, []int{5}
}

func (m *DeleteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReply.Unmarshal(m, b)
}
func (m *DeleteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReply.Marshal(b, m, deterministic)
}
func (m *DeleteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReply.Merge(m, src)
}
func (m *DeleteReply) XXX_Size() int {
	return xxx_messageInfo_DeleteReply.Size(m)
}
func (m *DeleteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReply proto.InternalMessageInfo

func (m *DeleteReply) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func init() {
	proto.RegisterEnum("com.ibm.cloudland.hypers.Kind", Kind_name, Kind_value)
	proto.RegisterType((*Hyper)(nil), "com.ibm.cloudland.hypers.Hyper")
	proto.RegisterType((*GetRequest)(nil), "com.ibm.cloudland.hypers.GetRequest")
	proto.RegisterType((*GetReply)(nil), "com.ibm.cloudland.hypers.GetReply")
	proto.RegisterType((*ListRequest)(nil), "com.ibm.cloudland.hypers.ListRequest")
	proto.RegisterType((*DeleteRequest)(nil), "com.ibm.cloudland.hypers.DeleteRequest")
	proto.RegisterType((*DeleteReply)(nil), "com.ibm.cloudland.hypers.DeleteReply")
}

func init() { proto.RegisterFile("hypers.proto", fileDescriptor_1e42abecf7719035) }

var fileDescriptor_1e42abecf7719035 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x6b, 0xe3, 0x30,
	0x14, 0x5c, 0xf9, 0x2b, 0xce, 0x4b, 0x36, 0x1b, 0x74, 0x58, 0x8c, 0x59, 0x76, 0x83, 0xd9, 0x90,
	0xd0, 0x83, 0x29, 0x2e, 0xfd, 0x01, 0x2d, 0x85, 0x14, 0x5a, 0x68, 0x51, 0x2f, 0xa5, 0x37, 0xc7,
	0x12, 0x8d, 0xa8, 0x23, 0xbb, 0xb6, 0x5c, 0xc8, 0xb9, 0xc7, 0x9e, 0xfa, 0x8f, 0x8b, 0xe4, 0xc4,
	0xf9, 0x00, 0x37, 0x37, 0x8d, 0x66, 0xa2, 0x99, 0x79, 0x2f, 0x86, 0xfe, 0x62, 0x95, 0xb3, 0xa2,
	0x0c, 0xf3, 0x22, 0x93, 0x19, 0xf6, 0x92, 0x6c, 0x19, 0xf2, 0xf9, 0x32, 0x4c, 0xd2, 0xac, 0xa2,
	0x69, 0x2c, 0x68, 0x58, 0xf3, 0xc1, 0x3b, 0x02, 0xfb, 0x5a, 0x1d, 0xf1, 0x00, 0x0c, 0x4e, 0x3d,
	0x34, 0x42, 0x53, 0x9b, 0x18, 0x9c, 0x62, 0x1f, 0xdc, 0x45, 0x56, 0x4a, 0x11, 0x2f, 0x99, 0x67,
	0x8e, 0xd0, 0xb4, 0x4b, 0x1a, 0x8c, 0x7f, 0x83, 0x53, 0xca, 0x58, 0x56, 0xa5, 0x67, 0x69, 0x66,
	0x8d, 0xd4, 0x6f, 0xf2, 0xb8, 0x60, 0x42, 0x72, 0xea, 0xd9, 0xfa, 0xa5, 0x06, 0x2b, 0x8e, 0x56,
	0x45, 0x2c, 0x79, 0x26, 0x3c, 0x67, 0x84, 0xa6, 0x26, 0x69, 0x70, 0xf0, 0x07, 0x60, 0xc6, 0x24,
	0x61, 0xaf, 0x15, 0x2b, 0xe5, 0x61, 0x92, 0xe0, 0x02, 0x5c, 0xcd, 0xe6, 0xe9, 0x0a, 0x9f, 0x83,
	0xad, 0x93, 0x6b, 0xba, 0x17, 0xfd, 0x0b, 0xdb, 0x9a, 0x85, 0xba, 0x15, 0xa9, 0xd5, 0xc1, 0x27,
	0x82, 0xde, 0x2d, 0x2f, 0x1b, 0x8b, 0xdd, 0xa0, 0xe8, 0x20, 0xe8, 0xb6, 0x9c, 0xb1, 0x57, 0x2e,
	0x02, 0xeb, 0x85, 0x0b, 0xaa, 0x87, 0x31, 0x88, 0xfe, 0xb6, 0x3b, 0xdf, 0x70, 0x41, 0x89, 0xd6,
	0x2a, 0x9f, 0x4a, 0x94, 0x49, 0x96, 0x33, 0xaa, 0x47, 0xe5, 0x92, 0x06, 0x07, 0xbf, 0xe0, 0xe7,
	0x15, 0x4b, 0x99, 0x64, 0xeb, 0x50, 0xc1, 0x04, 0x7a, 0x9b, 0x0b, 0x55, 0xd5, 0x83, 0x0e, 0xd5,
	0xb0, 0x8e, 0x68, 0x92, 0x0d, 0x3c, 0x19, 0x83, 0xa5, 0x3c, 0x70, 0x07, 0xcc, 0x38, 0x4d, 0x87,
	0x3f, 0x70, 0x77, 0x3d, 0x95, 0x21, 0x52, 0xc7, 0xf8, 0x99, 0x09, 0x39, 0x34, 0xa2, 0x0f, 0x03,
	0xfa, 0x7a, 0x0a, 0x0f, 0xac, 0x78, 0xe3, 0x09, 0xc3, 0x8f, 0xe0, 0xd4, 0x06, 0x78, 0xd2, 0x9e,
	0x7e, 0x2f, 0x93, 0x3f, 0x3e, 0x2e, 0x54, 0x59, 0xef, 0xc0, 0x9c, 0x31, 0x89, 0xff, 0xb7, 0xab,
	0xb7, 0xfb, 0xf5, 0x83, 0x23, 0x2a, 0xf5, 0xe0, 0x3d, 0x58, 0x6a, 0x5f, 0xf8, 0x1b, 0xff, 0x9d,
	0x7d, 0xfa, 0xc7, 0xfe, 0x07, 0xa7, 0xe8, 0xd2, 0x7d, 0x72, 0xea, 0x9b, 0xb9, 0xa3, 0x3f, 0x8a,
	0xb3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x3c, 0x55, 0x1c, 0x24, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HyperServiceClient is the client API for HyperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HyperServiceClient interface {
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (HyperService_ListClient, error)
}

type hyperServiceClient struct {
	cc *grpc.ClientConn
}

func NewHyperServiceClient(cc *grpc.ClientConn) HyperServiceClient {
	return &hyperServiceClient{cc}
}

func (c *hyperServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error) {
	out := new(DeleteReply)
	err := c.cc.Invoke(ctx, "/com.ibm.cloudland.hypers.HyperService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/com.ibm.cloudland.hypers.HyperService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (HyperService_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HyperService_serviceDesc.Streams[0], "/com.ibm.cloudland.hypers.HyperService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &hyperServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HyperService_ListClient interface {
	Recv() (*Hyper, error)
	grpc.ClientStream
}

type hyperServiceListClient struct {
	grpc.ClientStream
}

func (x *hyperServiceListClient) Recv() (*Hyper, error) {
	m := new(Hyper)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HyperServiceServer is the server API for HyperService service.
type HyperServiceServer interface {
	Delete(context.Context, *DeleteRequest) (*DeleteReply, error)
	Get(context.Context, *GetRequest) (*GetReply, error)
	List(*ListRequest, HyperService_ListServer) error
}

// UnimplementedHyperServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHyperServiceServer struct {
}

func (*UnimplementedHyperServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedHyperServiceServer) Get(ctx context.Context, req *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedHyperServiceServer) List(req *ListRequest, srv HyperService_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterHyperServiceServer(s *grpc.Server, srv HyperServiceServer) {
	s.RegisterService(&_HyperService_serviceDesc, srv)
}

func _HyperService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ibm.cloudland.hypers.HyperService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ibm.cloudland.hypers.HyperService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HyperServiceServer).List(m, &hyperServiceListServer{stream})
}

type HyperService_ListServer interface {
	Send(*Hyper) error
	grpc.ServerStream
}

type hyperServiceListServer struct {
	grpc.ServerStream
}

func (x *hyperServiceListServer) Send(m *Hyper) error {
	return x.ServerStream.SendMsg(m)
}

var _HyperService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.ibm.cloudland.hypers.HyperService",
	HandlerType: (*HyperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _HyperService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _HyperService_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _HyperService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hypers.proto",
}
