language: generic
sudo: required
services:
- docker
git:
  clone: true
before_install:
- ssh-keyscan $TEST_IP >> $HOME/.ssh/known_hosts
install:
- pwd
- ls -alrt
- ls -alrt ~/.ssh
- cat ~/.ssh/known_hosts
- cat ~/.ssh/authorized_keys
- cat ~/.ssh/config
- ls -alrt
- openssl aes-256-cbc -K $encrypted_e6df4bfe5d89_key -iv $encrypted_e6df4bfe5d89_iv
  -in skey.enc -out ~/.ssh/skey -d
- ls -alrt ~/.ssh
- chmod 600 ~/.ssh/skey
- ls -lrt deploy
- cat autocheck.sh
- bash ./autocheck.sh queue $TEST_IP
script:
- ssh -i ~/.ssh/skey cland@$TEST_IP 
- whoami
- cd /opt/cloudland/ && sudo bash ./autocheck.sh pull_request $TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_PULL_REQUEST_SLUG
- bash ./autocheck.sh test $TEST_IP
