language: generic
sudo: required
services:
  - docker
git:
  clone: false
before_install:
  # - docker pull $OS
  - sudo git clone --branch=$TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
install:
  - cd $TRAVIS_REPO_SLUG
  - docker build --build-arg BRANCH=$TRAVIS_BRANCH --build-arg REPO=$TRAVIS_REPO_SLUG -t centos_env .
script:
  - bash ./autocheck.sh test $TEST_ENV_IP