- name: install postgresql packages
  apt: 
    name: ['postgresql-all']
    state: present

- name: pg hba config
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/14/main/pg_hba.conf
  tags: [db_conf]

- name: start postgresql service
  systemd: 
    name: postgresql
    enabled: yes
    state: restarted
  tags: [pg_srv]

- name: run pg script
  script: postgres.sh  {{ db_passwd }}
  tags: [pg_sh]
  ignore_errors: yes
