- name: install nginx
  yum:
    name: ['nginx']
  tags: [nginx]

- name: nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  tags: [nginx]

- name: generate nginx certs
  script: gencert.sh
  tags: [nginx,ssl]

- name: nginx ssl config
  template:
    src: ssl.conf.j2
    dest: /etc/nginx/conf.d/ssl.conf
  tags: [nginx,console,ssl]

- name: start nginx service
  systemd:
    name: nginx
    enabled: yes
    daemon_reload: yes
    state: restarted
  tags: [nginx]
