- name: install nginx
  yum:
    name: ['nginx']
  tags: [nginx]

- name: nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  tags: [nginx]

- name: generate nginx certs
  script: gencert.sh
  tags: [nginx,ssl]

- name: nginx ssl config
  template:
    src: ssl.conf.j2
    dest: /etc/nginx/conf.d/ssl.conf
  tags: [nginx,console,ssl]

- name: start nginx service
  systemd:
    name: nginx
    enabled: yes
    daemon_reload: yes
    state: restarted
  tags: [nginx]

- name: get centos image
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: cland
  with_items:
    - {src: 'http://www.bluecat.ltd/repo/CentOS-7-x86_64-GenericCloud.qcow2', dest: '/opt/cloudland/cache/image/image-1.qcow2'}
    - {src: 'http://www.bluecat.ltd/repo/ubuntu1804.qcow2', dest: '/opt/cloudland/cache/image/image-2.qcow2'}
    - {src: 'http://www.bluecat.ltd/repo/xenial-server-cloudimg-amd64-disk1.img', dest: '/opt/cloudland/cache/image/image-3.qcow2'}
    - {src: 'http://www.bluecat.ltd/repo/rhcos-4.2.0-x86_64-installer-kernel', dest: '/opt/cloudland/cache/image/rhcos-installer-kernel'}
    - {src: 'http://www.bluecat.ltd/repo/rhcos-4.2.0-x86_64-installer-initramfs.img', dest: '/opt/cloudland/cache/image/rhcos-installer-initramfs.img'}
  tags: [image]
