---
- name: Setting up backend
  hosts: hyper
  vars:
     # Firewall setup
     gluster_infra_fw_ports:
        - 2049/tcp
        - 54321/tcp
        - 5900/tcp
        - 5900-6923/tcp
        - 5666/tcp
        - 16514/tcp
        - 24007/tcp
     # Set a disk type, Options: JBOD, RAID6, RAID10
     gluster_infra_disktype: JBOD
     # RAID6 and RAID10 diskcount (Needed only when disktype is raid)
     gluster_infra_diskcount: 12
     # Stripe unit size always in KiB
     gluster_infra_stripe_unit_size: 128
     # Variables for creating volume group
     gluster_infra_volume_groups:
       - { vgname: 'vg_sdb', pvname: '/dev/sdb' }
     # Create thinpools
     gluster_infra_thinpools:
       - {vgname: 'vg_sdb', thinpoolname: 'sdb_thinpool', thinpoolsize: '1500G', poolmetadatasize: '2G'}
     # Create a thin volume
     gluster_infra_lv_logicalvols:
       - { vgname: 'vg_sdb', thinpool: 'sdb_thinpool', lvname: 'vg_sdb_thinlv', lvsize: '2000G' }
     # Mount the devices
     gluster_infra_mount_devices:
       - { path: '/gluster/thinlv1', vgname: 'vg_sdb', lvname: 'vg_sdb_thinlv' }
  roles:
     - ginfra

- name: Create Gluster cluster
  hosts: hyper
  vars:
    # gluster volume
    gluster_cluster_hosts:
      - cath-test0
      - cath-test1
      - cath-test2
      - cath-test3
    gluster_cluster_volume: testvol
    gluster_cluster_transport: 'tcp'
    gluster_cluster_force: 'yes'
    gluster_cluster_bricks: '/gluster/thinlv1,/gluster/thinlv2,/gluster/thinlv3'
    # variables to create specific type of the volume
    gluster_cluster_replica_count: 3
    gluster_cluster_arbiter_count: 1
    # variables to set specific volume options
    #gluster_cluster_options: 'performance.cache-size:256MB'
  roles:
    - gcluster
