#!/bin/sh -x

OS_TYPE=$(uname)
if [[ ${OS_TYPE} = "AIX" ]]
then
    make -f Makefile.aix clean
    make -f Makefile.aix all
else
    CURR_CHIP=$(arch)
    if [[ ${CURR_CHIP} == 'ppc64' ]]
    then
        make clean
        make all
    else
        if [[ ${CURR_CHIP} == 'i386' || ${CURR_CHIP} == 'i686' ]]
        then
            make clean_32
            make all_32
        else
            if [[ ${CURR_CHIP} == 'x86_64' ]]
            then
                make all
            fi
        fi
    fi
fi
