- name: ensure hostname set correctly
  hostname: name={{inventory_hostname}}
  tags: [hosts]

- name: ensure hosts set correctly
  template: src=hosts.j2 dest=/etc/hosts
  tags: [hosts]

- name: change system max open files
  copy:
    src: files/limits.conf
    dest: /etc/security/limits.d/cloudland.conf
  tags: [sysfd]

- name: install ntp service
  apt: name=ntp state=latest
  tags: [ntp]

- name: start ntp service
  service: name=ntp state=started enabled=yes
  tags: [ntp]

- name: upgrade all packages
  apt: 
    name: '*'
    state: latest
  tags: [upgrade]

- name: create cland user
  user:
    name: cland
    create_home: yes
    shell: '/bin/bash'

- name: config cland user sudoer
  lineinfile: 
    dest: /etc/sudoers.d/cland
    state: present
    create: true
    line: 'cland ALL=(ALL) NOPASSWD:ALL'

- name: mask firewall service
  systemd:
    service: ufw
    masked: yes
    state: stopped
  tags: [firewall]
  ignore_errors: yes

- name: allow basic firewall rules
  script: firewall.sh
  tags: [firewall]
