basePath: /api/v1
definitions:
  apis.APIError:
    properties:
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
  apis.User:
    properties:
      Org:
        type: string
      access_token:
        type: string
      name:
        type: string
    type: object
  apis.UserPayload:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  description: APIs for CloudLand Functions
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: CloudLand API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: get token by user name
      parameters:
      - description: User Credential
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/apis.UserPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apis.User'
        "400":
          description: Need user with password
          schema:
            $ref: '#/definitions/apis.APIError'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/apis.APIError'
      summary: login to get the accesstoken
      tags:
      - Authorities
swagger: "2.0"
