swagger: '2.0'
info:
  title: Cloudland API compatible openstack API,
  version: v3,
  description: Clandland API to compatible openstack API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: spark.liu@cn.ibm.com
    name: Spark.liu
paths:
  /identity:
    get:
      consumes: [application/json]
      produces: [application/json]
      tags: [keystone]
      description: 'redirect to identity auth point'
      responses:
        300:
          description: redirect connection
          headers:
            Vary:
              type: string
              description: X-Auth-Token
              default: X-Auth-Token
              enum:
              - X-Auth-Token
            x-openstack-request-id: {type: string, description: 'request-id'}
          schema:
            type: object
            required:
            - versions
            properties:
              versions:
                $ref: '#/definitions/versions'

  /identity/v3/auth/tokens:
    post:
      consumes: [application/json]
      produces: [application/json]
      tags: [keystone]
      description: Create a new token
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            auth:
              type: object
              properties:
                scope:
                  type: object
                  properties:
                    project:
                      type: object
                      properties:
                        domain:
                          type: object
                          properties:
                            id: {type: string, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: default}
                        name: {type: string, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: demo}
                identity:
                  type: object
                  properties:
                    methods:
                      type: array
                      items: {type: string, enum: [password], example: password}
                    password:
                      type: object
                      properties:
                        user:
                          type: object
                          properties:
                            name: {type: string,  pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: admin}
                            password: {type: string, example: adminpwd}
                            domain:
                              type: object
                              properties:
                                id: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: default}
      responses:
        201:
          description: successful operation
          headers:
            Vary:
              type: string
              description: X-Auth-Token
              default: X-Auth-Token
              enum:
              - X-Auth-Token
            Content-Length:
              type: integer
            X-Subject-Token:
              type: string
          schema:
            type: object
            required:
            - token
            properties:
              token:
                $ref: '#/definitions/token'
  /v2.0/networks:
    get:
      tags: [neutron]
      operationId: listNetworks
      summary: List networks
      description: |
        Lists networks to which the specified tenant has access.
      produces: [application/json]
      responses:
        200:
          description: 200 response
          headers:
            Vary:
              type: string
              description: X-Auth-Token
              default: X-Auth-Token
              enum:
              - X-Auth-Token
            Content-Length:
              type: integer
            X-Subject-Token:
              type: string
          schema:
            type: object
            required:
            - token
            properties:
              networks:
                $ref: '#/definitions/networks'
    post:
      tags: [neutron]
      operationId: createNetwork
      summary: create network without subnet
      description: |
        create a network
      consumes: [application/json]
      produces: [application/json]
      parameters:
        - in: body
          name: body
          required: true
          schema:
            properties:
              network:
                type: object
                properties:
                  admin_state_up: {type: boolean, example: true}
                  name: {type: string, example: 'net1'}
                  provider:network_type: {type: string, enum: ['vlan', 'vxlan', 'gre', 'flat']}
                  provider:physical_network: {type: string, enum: ['public', 'private'], example: public}
                  provider:segmentation_id: {type: string, example: '16169'}
                  router:external: {type: boolean, example: false}
                  qos_policy_id: {type: string, example: '6a8454ade84346f59e8d40665f878b2e'}
      responses:
        200:
          description: 200 response
          headers:
            Vary:
              type: string
              description: X-Auth-Token
              default: X-Auth-Token
              enum:
              - X-Auth-Token
            Content-Length:
              type: integer
            X-Subject-Token:
              type: string
          schema:
            type: object
            required:
            - token
            properties:
              network:
                $ref: '#/definitions/network'
  /v2.0/subnets:
    get:
      tags: [neutron]
      operationId: listSubnets
      summary: list subnets
      description: |
        List subnets
      produces: [application/json]
      responses:
        200:
          description: 200 response
          headers:
            Vary:
              type: string
              description: X-Auth-Token
              default: X-Auth-Token
              enum:
              - X-Auth-Token
            Content-Length:
              type: integer
            X-Subject-Token:
              type: string
          schema:
              type: object
              required:
              - subnets
              properties:
                subnets:
                  $ref: '#/definitions/subnets'
    post:
      tags: [neutron]
      operationId: createSubnet
      summary: create subnets
      description: |
        create a subnet with network_id
      consumes: [application/json]
      produces: [application/json]
      parameters:
        - in: body
          name: body
          required: true
          schema:
            properties:
              subnet:
                type: object
                properties:
                  network_id: {type: string, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: '1841f2adad3a4b4aa6485fb4e3a3fda1'}
                  ip_version: {type: integer, enum: [4, 6], example: 6}
                  cidr: {type: string, example: '10.0.0.1/24'}
                  name: {type: string, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 'net1'}
      responses:
          200:
            description: 200 response
            headers:
              Vary:
                type: string
                description: X-Auth-Token
                default: X-Auth-Token
                enum:
                - X-Auth-Token
              Content-Length:
                type: integer
              X-Subject-Token:
                type: string
            schema:
              type: object
              required:
              - subnet
              properties:
                subnet:
                  $ref: '#/definitions/subnet'
definitions:
  token:
    type: object
    properties:
      is_domain: {type: boolean, example: false}
      methods:
        type: array
        items: {type: string, enum: [password], example: 'password'}
      roles:
        type: array
        items:
          type: object
          properties:
            id: {type: string, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: '1841f2adad3a4b4aa6485fb4e3a3fda1'}
            name: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 'member'}
      expires_at: {type: string, format: date-time, example: "2015-11-06T14:32:17.893797Z"}
      issued_at: {type: string, format: date-time, example: "2015-11-06T14:32:17.893797Z"}
      project:
        type: object
        properties:
          domain:
            type: object
            properties:
              id: {type: string, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: '1841f2adad3a4b4aa6485fb4e3a3fda1'}
              name: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 'member'}
          id: {type: string, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: '1841f2adad3a4b4aa6485fb4e3a3fda1'}
          name: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 'member'}
      catalog:
        type: array
        items:
          type: object
          properties:
            endpoints:
              type: array
              items:
                type: object
                properties:
                  url: {type: string, format: url, pattern: '^http(s)?:\/\/([^\/?#]*)([^?#]*)(\?([^#]*))?(#(.*))?$', example: "http://192.168.10.16/volume/v3/3b6825911eaa44059c525888dc32713b"}
                  interface: {type: string, enum: [public, private], pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: public}
                  region: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 'RegionOne'}
                  region_id: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 'RegionOne'}
                  id: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 'Regdb9895a3f6b840d98581dbee86f49069ionOne'}
            type: {type: string, enum: ["volumev3"], example: "volumev3"}
            id: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 'db9895a3f6b840d98581dbee86f49069'}
            name: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 'member'}
      user:
        type: object
        properties:
          password_expires_at: {type: string, format: date-time, example: "2015-11-06T14:32:17.893797Z"}
          domain:
            type: object
            properties:
              id: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: default}
              name: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: default}
          id: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: default}
          name: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: default}

  versions:
    type: object
    properties:
      values:
        type: array
        items:
          type: object
          properties:
            status: {type: string, enum: [stable], pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: stable}
            updated: {type: string, format: date-time, example: "2015-11-06T14:32:17.893797Z"}
            media-types:
              type: array
              items:
                type: object
                properties:
                  base: {type: string, enum: ['application/json'], example: 'application/json'}
                  type: {type: string, enum: ['application/json'], example: 'application/vnd.openstack.identity-v3+json'}
            id: {type: string, enum: ['v3.10'], example: 'v3.10'}
            links:
              type: array
              items:
                type: object
                properties:
                  href: {type: string, pattern: '^http(s)?:\/\/([^\/?#]*)([^?#]*)(\?([^#]*))?(#(.*))?$', example: 'http://192.168.10.16/identity/v3/'}
                  rel: {type: string, enum: [self, remote], example: "self"}
  networks:
   type: array
   items:
      $ref: '#/definitions/network'
  network:
    type: object
    properties:
      admin_state_up: {type: boolean, example: true}
      availability_zone_hints: {type: array, items: {type: string, example: 'nova'}}
      availability_zones: {type: array, items: {type: string, example: 'nova'}}
      created_at: {type: string, format: date-time, example: '2016-03-08T20:19:41'}
      dns_domain: {type: string, example: 'my-domain.org.'}
      id: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 'd32019d3-bc6e-4319-9c1d-6722fc136a22'}
      ipv4_address_scope: {type: string, example: null}
      ipv6_address_scope:  {type: string, example: null}
      l2_adjacency: {type: boolean, example: false}
      mtu: {type: integer, example: 1500}
      name: {type: string, enum: [stable], pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: net1}
      port_security_enabled:  {type: boolean, example: true}
      project_id: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 4fd44f30292945e481c7b8a0c8908869}
      qos_policy_id: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: '6a8454ade84346f59e8d40665f878b2e'}
      revision_number: {type: integer, example: 1}
      router:external: {type: boolean, example: false}
      shared: {type: boolean, example: false}
      status: {type: string, enum: ['ACTIVE', 'DISABLE', 'INACTIVE'], example: "ACTIVE"}
      subnets: {type: array, items: {type: string, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: '54d6f61d-db07-451c-9ab3-b9609b6b6f0b'}}
      tenant_id: {type: string, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: '4fd44f30292945e481c7b8a0c8908869'}
      updated_at: {type: string, format: date-time, example: '2016-03-08T20:19:41'}
      vlan_transparent: {type: boolean, example: false}
      description: {type: string, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: ''}
      is_default: {type: boolean, example: false}
      provider:network_type: {type: string, enum: ['vlan', 'vxlan', 'gre', 'flat'], example: 'vxlan'}
      provider:segmentation_id: {type: string, example: '190190'}
  subnets:
    type: array
    items:
       $ref: '#/definitions/subnet'
  subnet:
    type: object
    properties:
      name: {type: string, enum: [stable], pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: net1}
      enable_dhcp: {type: boolean, example: true}
      network_id: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 'd32019d3-bc6e-4319-9c1d-6722fc136a22'}
      segment_id: {type: string, example: null}
      project_id: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 4fd44f30292945e481c7b8a0c8908869}
      tenant_id: {type: string, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: '4fd44f30292945e481c7b8a0c8908869'}
      dns_nameservers: {type: array, items: {type: string, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: '54d6f61d-db07-451c-9ab3-b9609b6b6f0b'}}
      dns_publish_fixed_ip: {type: boolean, example: true}
      allocation_pools:
        type: array
        items:
          type: object
          properties:
            start: {type: string, format: ipv4, example: '10.0.0.2'}
            end: {type: string, format: ipv4, example: '10.0.0.5'}
      host_routes:
        type: array
        items:
          type: object
          properties:
             destination: {type: string, format: ipv4, example: '10.0.0.2'}
             nexthop: {type: string, format: ipv4, example: '10.0.0.2'}
      ip_version: {type: integer, enum: [4, 6], example: 6}
      gateway_ip: {type: string, format: ipv4, example: '10.0.0.1'}
      cidr: {type: string, example: '10.0.0.1/24'}
      id: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 'd32019d3-bc6e-4319-9c1d-6722fc136a22'}
      created_at: {type: string, format: date-time, example: '2016-03-08T20:19:41'}
      description: {type: string, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: ''}
      ipv6_address_mode: {type: string, enum: ['slaac', 'dhcpv6-stateful', 'dhcpv6-stateless', 'null']}
      ipv6_ra_mode: {type: string, enum: ['slaac', 'dhcpv6-stateful', 'dhcpv6-stateless', 'null']}
      revision_number: {type: integer, example: 0}
      service_types: {type: array, items: {type: string}, example: []}
      subnetpool_id: {type: string, format: name, pattern: '^[A-Za-z][-A-Za-z0-9_]*$', example: 'd32019d3-bc6e-4319-9c1d-6722fc136a22'}
      updated_at: {type: string, format: date-time, example: '2016-03-08T20:19:41'}
