- name: base
  hosts: all
  roles:
    - {role: base, become: yes, tags: [base]}

# deploy hypers
- name: install hyper
  hosts: hyper
  become_user: root
  roles:
    - {role: hyper, become: yes, tags: [hyper]}

# deploy cloudland
- name: install cland
  hosts: cland
  roles:
    - {role: cland, become: yes, tags: [cland]}

# deploy web
- name: install web
  hosts: web
  become_user: root
  roles:
    - {role: web, become: yes, tags: [web]}

# deploy nginx
- name: install nginx
  hosts: web
  become_user: root
  roles:
    - {role: nginx, become: yes, tags: [nginx]}

# deploy database
- name: install database
  hosts: database
  become_user: root
  roles:
    - {role: database, become: yes, tags: [database]}

# deploy wds storage
- name: install wds
  hosts: wds
  become_user: root
  roles:
    - {role: wds, become: yes, tags: [wds]}

# deploy monitor 
- name: install monitor
  hosts: monitor
  become_user: root
  roles:
    - {role: monitor, become: yes, tags: [monitor]}
