- name: base
  hosts: all
  roles:
    - {role: base, become: yes}

# deploy hypers
- name: install hyper
  hosts: hyper
  become_user: root
  roles:
    - {role: hyper, become: yes}

# deploy root node
- name: install cland
  hosts: cland
  roles:
    - {role: cland, become: yes}

# deploy web
- name: install web
  hosts: web
  become_user: root
  roles:
    - {role: web, become: yes}

# deploy database
- name: install database
  hosts: database
  become_user: root
  roles:
    - {role: database, become: yes}

# deploy wds storage
- name: install wds
  hosts: wds
  become_user: root
  roles:
    - {role: wds, become: yes}
