- name: base
  hosts: all
  roles:
    - {role: base, become: yes}

# deploy hypers
- name: install hyper
  hosts: hyper
  become_user: root
  roles:
    - {role: hyper, become: yes, tags: [hyper]}
    - {role: imgrepo, become: yes, tags: [nginx]}

# deploy root node
- name: install cland
  hosts: cland
  roles:
    - {role: cland, become: yes, tags: [cland]}

# deploy web
- name: install web
  hosts: web
  become_user: root
  roles:
    - {role: web, become: yes, tags: [web]}

# deploy database
- name: install database
  hosts: database
  become_user: root
  roles:
    - {role: database, become: yes, tags: [database]}
