// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateImageMemberParamsBody create image member params body
//
// swagger:model createImageMemberParamsBody
type CreateImageMemberParamsBody struct {

	// member
	// Example: 8989447062e04a818baf9e073fd04fa7
	// Required: true
	Member *string `json:"member"`
}

// Validate validates this create image member params body
func (m *CreateImageMemberParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMember(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateImageMemberParamsBody) validateMember(formats strfmt.Registry) error {

	if err := validate.Required("member", "body", m.Member); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create image member params body based on context it is used
func (m *CreateImageMemberParamsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateImageMemberParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateImageMemberParamsBody) UnmarshalBinary(b []byte) error {
	var res CreateImageMemberParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
