// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Flavor flavor
//
// swagger:model flavor
type Flavor struct {

	// o s f l v e x t d a t a ephemeral
	// Example: 0
	OSFLVEXTDATAEphemeral int64 `json:"OS-FLV-EXT-DATA:ephemeral,omitempty"`

	// description
	// Pattern: ^[A-Za-z][-A-Za-z0-9_]*$
	Description string `json:"description,omitempty"`

	// disk
	// Example: 100
	Disk int32 `json:"disk,omitempty"`

	// id
	// Example: d32019d3-bc6e-4319-9c1d-6722fc136a22
	// Pattern: ^[A-Za-z][-A-Za-z0-9_]*$
	ID string `json:"id,omitempty"`

	// links
	Links Links `json:"links,omitempty"`

	// name
	// Example: net1
	// Pattern: ^[A-Za-z][-A-Za-z0-9_]*$
	Name string `json:"name,omitempty"`

	// os flavor access is public
	// Example: false
	OsFlavorAccessIsPublic bool `json:"os-flavor-access:is_public,omitempty"`

	// ram
	// Example: 100
	RAM int32 `json:"ram,omitempty"`

	// rxtx factor
	// Example: 2
	RxtxFactor float32 `json:"rxtx_factor,omitempty"`

	// swap
	// Example: 100
	Swap int32 `json:"swap,omitempty"`

	// vcpus
	// Example: 2
	Vcpus int32 `json:"vcpus,omitempty"`
}

// Validate validates this flavor
func (m *Flavor) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Flavor) validateDescription(formats strfmt.Registry) error {
	if swag.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.Pattern("description", "body", m.Description, `^[A-Za-z][-A-Za-z0-9_]*$`); err != nil {
		return err
	}

	return nil
}

func (m *Flavor) validateID(formats strfmt.Registry) error {
	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.Pattern("id", "body", m.ID, `^[A-Za-z][-A-Za-z0-9_]*$`); err != nil {
		return err
	}

	return nil
}

func (m *Flavor) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(m.Links) { // not required
		return nil
	}

	if err := m.Links.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("links")
		}
		return err
	}

	return nil
}

func (m *Flavor) validateName(formats strfmt.Registry) error {
	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.Pattern("name", "body", m.Name, `^[A-Za-z][-A-Za-z0-9_]*$`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this flavor based on the context it is used
func (m *Flavor) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Flavor) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Links.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("links")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Flavor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Flavor) UnmarshalBinary(b []byte) error {
	var res Flavor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
