// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Link link
// swagger:model link
type Link struct {

	// href
	// Required: true
	// Pattern: ^http(s)?:\/\/([^\/?#]*)([^?#]*)(\?([^#]*))?(#(.*))?$
	Href *string `json:"href"`

	// rel
	// Required: true
	// Pattern: ^[A-Za-z][-A-Za-z0-9_]*$
	// Enum: [self bookmark]
	Rel *string `json:"rel"`
}

// Validate validates this link
func (m *Link) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHref(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRel(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Link) validateHref(formats strfmt.Registry) error {

	if err := validate.Required("href", "body", m.Href); err != nil {
		return err
	}

	if err := validate.Pattern("href", "body", string(*m.Href), `^http(s)?:\/\/([^\/?#]*)([^?#]*)(\?([^#]*))?(#(.*))?$`); err != nil {
		return err
	}

	return nil
}

var linkTypeRelPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["self","bookmark"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		linkTypeRelPropEnum = append(linkTypeRelPropEnum, v)
	}
}

const (

	// LinkRelSelf captures enum value "self"
	LinkRelSelf string = "self"

	// LinkRelBookmark captures enum value "bookmark"
	LinkRelBookmark string = "bookmark"
)

// prop value enum
func (m *Link) validateRelEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, linkTypeRelPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Link) validateRel(formats strfmt.Registry) error {

	if err := validate.Required("rel", "body", m.Rel); err != nil {
		return err
	}

	if err := validate.Pattern("rel", "body", string(*m.Rel), `^[A-Za-z][-A-Za-z0-9_]*$`); err != nil {
		return err
	}

	// value enum
	if err := m.validateRelEnum("rel", "body", *m.Rel); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Link) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Link) UnmarshalBinary(b []byte) error {
	var res Link
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
