// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostIdentityV3AuthTokensParamsBodyAuthIdentityPassword post identity v3 auth tokens params body auth identity password
// swagger:model postIdentityV3AuthTokensParamsBodyAuthIdentityPassword
type PostIdentityV3AuthTokensParamsBodyAuthIdentityPassword struct {

	// user
	User *PostIdentityV3AuthTokensParamsBodyAuthIdentityPasswordUser `json:"user,omitempty"`
}

// Validate validates this post identity v3 auth tokens params body auth identity password
func (m *PostIdentityV3AuthTokensParamsBodyAuthIdentityPassword) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostIdentityV3AuthTokensParamsBodyAuthIdentityPassword) validateUser(formats strfmt.Registry) error {

	if swag.IsZero(m.User) { // not required
		return nil
	}

	if m.User != nil {
		if err := m.User.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("user")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostIdentityV3AuthTokensParamsBodyAuthIdentityPassword) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostIdentityV3AuthTokensParamsBodyAuthIdentityPassword) UnmarshalBinary(b []byte) error {
	var res PostIdentityV3AuthTokensParamsBodyAuthIdentityPassword
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
